/**
 * Static catalogue of MTR heavy-rail lines: operating hours, terminus,
 * frequency, and ordered station list. Values are approximate and based
 * on the public MTR timetable as of 2025/26. They change occasionally
 * (holidays, typhoons, engineering works) — treat them as a reference.
 */

export const MTR_LINE_DETAILS = {
  AEL: {
    code: 'AEL',
    name: 'Airport Express',
    nameZh: '機場快綫',
    color: '#1c7670',
    firstTrain: '05:54',
    lastTrain: '00:48',
    headwayMinutes: 12,
    interchangeOnly: false,
    note: 'Limited-stop express linking Hong Kong Station with the airport in 24 minutes.',
    stations: [
      'Hong Kong',
      'Kowloon',
      'Tsing Yi',
      'Airport',
      'AsiaWorld-Expo',
    ],
  },
  TCL: {
    code: 'TCL',
    name: 'Tung Chung Line',
    nameZh: '東涌綫',
    color: '#f7943e',
    firstTrain: '05:54',
    lastTrain: '01:15',
    headwayMinutes: 8,
    stations: [
      'Hong Kong',
      'Kowloon',
      'Olympic',
      'Nam Cheong',
      'Lai King',
      'Tsing Yi',
      'Sunny Bay',
      'Tung Chung',
    ],
  },
  ISL: {
    code: 'ISL',
    name: 'Island Line',
    nameZh: '港島綫',
    color: '#0070b9',
    firstTrain: '06:00',
    lastTrain: '01:00',
    headwayMinutes: 3,
    stations: [
      'Kennedy Town',
      'HKU',
      'Sai Ying Pun',
      'Sheung Wan',
      'Central',
      'Admiralty',
      'Wan Chai',
      'Causeway Bay',
      'Tin Hau',
      'Fortress Hill',
      'North Point',
      'Quarry Bay',
      'Tai Koo',
      'Sai Wan Ho',
      'Shau Kei Wan',
      'Heng Fa Chuen',
      'Chai Wan',
    ],
  },
  TWL: {
    code: 'TWL',
    name: 'Tsuen Wan Line',
    nameZh: '荃灣綫',
    color: '#e2231a',
    firstTrain: '05:58',
    lastTrain: '01:00',
    headwayMinutes: 3,
    stations: [
      'Central',
      'Admiralty',
      'Tsim Sha Tsui',
      'Jordan',
      'Yau Ma Tei',
      'Mong Kok',
      'Prince Edward',
      'Sham Shui Po',
      'Cheung Sha Wan',
      'Lai Chi Kok',
      'Mei Foo',
      'Lai King',
      'Kwai Fong',
      'Kwai Hing',
      'Tai Wo Hau',
      'Tsuen Wan',
    ],
  },
  KTL: {
    code: 'KTL',
    name: 'Kwun Tong Line',
    nameZh: '觀塘綫',
    color: '#00a040',
    firstTrain: '05:50',
    lastTrain: '00:55',
    headwayMinutes: 3,
    stations: [
      'Whampoa',
      'Ho Man Tin',
      'Yau Ma Tei',
      'Mong Kok',
      'Prince Edward',
      'Shek Kip Mei',
      'Kowloon Tong',
      'Lok Fu',
      'Wong Tai Sin',
      'Diamond Hill',
      'Choi Hung',
      'Kowloon Bay',
      'Ngau Tau Kok',
      'Kwun Tong',
      'Lam Tin',
      'Yau Tong',
      'Tiu Keng Leng',
    ],
  },
  TKL: {
    code: 'TKL',
    name: 'Tseung Kwan O Line',
    nameZh: '將軍澳綫',
    color: '#7d499d',
    firstTrain: '06:00',
    lastTrain: '01:05',
    headwayMinutes: 3,
    stations: [
      'North Point',
      'Quarry Bay',
      'Yau Tong',
      'Tiu Keng Leng',
      'Tseung Kwan O',
      'Hang Hau',
      'Po Lam',
      'LOHAS Park',
    ],
  },
  EAL: {
    code: 'EAL',
    name: 'East Rail Line',
    nameZh: '東鐵綫',
    color: '#5eb6e4',
    firstTrain: '05:28',
    lastTrain: '00:25',
    headwayMinutes: 4,
    note: 'Cross-harbour service via Admiralty; First-Class compartments available.',
    stations: [
      'Admiralty',
      'Exhibition Centre',
      'Hung Hom',
      'Mong Kok East',
      'Kowloon Tong',
      'Tai Wai',
      'Sha Tin',
      'Fo Tan',
      'Racecourse',
      'University',
      'Tai Po Market',
      'Tai Wo',
      'Fanling',
      'Sheung Shui',
      'Lo Wu',
      'Lok Ma Chau',
    ],
  },
  TML: {
    code: 'TML',
    name: 'Tuen Ma Line',
    nameZh: '屯馬綫',
    color: '#9a3b26',
    firstTrain: '05:30',
    lastTrain: '00:30',
    headwayMinutes: 4,
    note: "Hong Kong's longest line: 27 stations from Wu Kai Sha to Tuen Mun (about 75 minutes end-to-end).",
    stations: [
      'Wu Kai Sha',
      'Ma On Shan',
      'Heng On',
      'Tai Shui Hang',
      'Shek Mun',
      'City One',
      'Sha Tin Wai',
      'Che Kung Temple',
      'Tai Wai',
      'Hin Keng',
      'Diamond Hill',
      'Kai Tak',
      'Sung Wong Toi',
      'To Kwa Wan',
      'Ho Man Tin',
      'Hung Hom',
      'East Tsim Sha Tsui',
      'Austin',
      'Nam Cheong',
      'Mei Foo',
      'Tsuen Wan West',
      'Kam Sheung Road',
      'Yuen Long',
      'Long Ping',
      'Tin Shui Wai',
      'Siu Hong',
      'Tuen Mun',
    ],
  },
  SIL: {
    code: 'SIL',
    name: 'South Island Line',
    nameZh: '南港島綫',
    color: '#bac429',
    firstTrain: '06:00',
    lastTrain: '01:00',
    headwayMinutes: 4,
    stations: [
      'Admiralty',
      'Ocean Park',
      'Wong Chuk Hang',
      'Lei Tung',
      'South Horizons',
    ],
  },
  DRL: {
    code: 'DRL',
    name: 'Disneyland Resort Line',
    nameZh: '迪士尼綫',
    color: '#f173ac',
    firstTrain: '06:05',
    lastTrain: '00:48',
    headwayMinutes: 8,
    note: 'Shuttle between Sunny Bay (interchange with TCL) and Disneyland Resort.',
    stations: ['Sunny Bay', 'Disneyland Resort'],
  },
};

export function getMtrLineDetails(code) {
  return MTR_LINE_DETAILS[String(code).toUpperCase()] ?? null;
}

export function listMtrLineDetails() {
  return Object.values(MTR_LINE_DETAILS).map((line) => ({
    ...line,
    stationCount: line.stations.length,
  }));
}
